data:
    name: hitgraphs
    input_dir: /global/cscratch1/sd/xju/heptrkx/data/hitgraphs_001
    n_train: 16384
    n_valid: 2048
    batch_size: 1
    n_workers: 6

experiment:
    name: gnn
    output_dir: /global/cscratch1/sd/sfarrell/heptrkx/results/gnnsegclf_small_002

training:
    n_epochs: 32

model:
    model_type: 'gnn_segment_classifier'
    input_dim: 3
    hidden_dim: 64
    n_iters: 4
    loss_func: 'binary_cross_entropy'
    optimizer: 'Adam'
    learning_rate: 0.001

